### ISSUE TITLE
Styled assistant modal component's avatar image cannot be changed.

### ISSUE THREAD

**Issue by hiroaki2020** [Yonom/assistant-ui#1197]
I cannot change assistant modal component default avatar img while it is working properly.
I also confirmed that span element with aui-avatar-fallback class and innerText "A" is always rendered instead and that strings prop is working.
Welcome message prop is not working as well.

```
<AssistantModal.Root config={{
    assistantAvatar: {
        src: "/path/to/img",
        alt: "Test Avatar"
    }
}}>
  <AssistantModal.Trigger />
  <AssistantModal.Content>
    <Thread assistantMessage={{ components: { Text: MarkdownText } }} />
  </AssistantModal.Content>
</AssistantModal.Root>
```

**Comment by Yonom** [comment]
Hey, what's happening is that you're setting ThreadConfig in two places:

- on AssistantModal.Root via assistantAvatar
- on Thread via assistantMessage

This causes the ThreadConfig of the AssistantModal.Root to be entirely overwritten. The fix for you is to merge the two declarations, either specify all config on Thread or on AssistantModal.Root

The current behavior is unintuitive, we should handle this better in the library. I will keep the issue option until a better solution is implemented in the library

**Comment by Yonom** [comment]
assistant-ui now throws an error instead of silently overwriting the ThreadConfig if you use nested ThreadConfigs

https://github.com/Yonom/assistant-ui/pull/1200

In the future, we might consider merging the configs instead
